- name: Anchore Container Scan
  # You may pin to the exact commit or the version.
  # uses: anchore/scan-action@ef959730f71411d57975163161075b8262f7ef26
  uses: anchore/scan-action@v3.0.0
  with:
    # The image to scan. This option is mutually exclusive with "path". 
    image: turbonomic/kubeturbo:8.3.1
    # Set this to any value to enable verbose debug output
    #debug: # optional, default is false
    # Set to false to avoid failing based on severity-cutoff. Default is to fail when severity-cutoff is reached (or surpassed)
    fail-build: false
    # Generate a SARIF report and set the `sarif` output parameter after successful action execution.  This report is compatible with GitHub Automated Code Scanning (ACS), as the artifact to upload for display as a Code Scanning Alert report.
    acs-report-enable: true
    # Optionally specify the minimum vulnerability severity to trigger an "error" level ACS result.  Valid choices are "negligible", "low", "medium", "high" and "critical".  Any vulnerability with a severity less than this value will lead to a "warning" result.  Default is "medium".
    # severity-cutoff: # optional, default is medium
